
package it.lmpetrella.tutorial.webservices.wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SayHelloService", targetNamespace = "http://wsServer.webservices.tutorial.lmpetrella.it/", wsdlLocation = "http://localhost:8080/wsServerExample?wsdl")
public class SayHelloService
    extends Service
{

    private final static URL SAYHELLOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.lmpetrella.tutorial.webservices.wsClient.SayHelloService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.lmpetrella.tutorial.webservices.wsClient.SayHelloService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/wsServerExample?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/wsServerExample?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAYHELLOSERVICE_WSDL_LOCATION = url;
    }

    public SayHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayHelloService() {
        super(SAYHELLOSERVICE_WSDL_LOCATION, new QName("http://wsServer.webservices.tutorial.lmpetrella.it/", "SayHelloService"));
    }

    /**
     * 
     * @return
     *     returns SayHello
     */
    @WebEndpoint(name = "SayHelloPort")
    public SayHello getSayHelloPort() {
        return super.getPort(new QName("http://wsServer.webservices.tutorial.lmpetrella.it/", "SayHelloPort"), SayHello.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHello
     */
    @WebEndpoint(name = "SayHelloPort")
    public SayHello getSayHelloPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServer.webservices.tutorial.lmpetrella.it/", "SayHelloPort"), SayHello.class, features);
    }

}
