
package it.lmpetrella.tutorial.webservices.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SayHello", targetNamespace = "http://wsServer.webservices.tutorial.lmpetrella.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGreeting", targetNamespace = "http://wsServer.webservices.tutorial.lmpetrella.it/", className = "it.lmpetrella.tutorial.webservices.wsClient.GetGreeting")
    @ResponseWrapper(localName = "getGreetingResponse", targetNamespace = "http://wsServer.webservices.tutorial.lmpetrella.it/", className = "it.lmpetrella.tutorial.webservices.wsClient.GetGreetingResponse")
    public String getGreeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
